spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/acclwangkai/spring-cloud-demo/     # 配置git仓库的地址
          search-paths: config-repo                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: acclwangkai                                             # git仓库的账号
          password: a502392996                                            # git仓库的密码
server:
  port: 8767
